# Generated by Django 4.0.4 on 2022-06-08 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsubtag',
            name='image',
            field=models.ImageField(null=True, upload_to='subtag-image'),
        ),
        migrations.AddField(
            model_name='productsubtag',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='subtag-thumbnail'),
        ),
        migrations.AddField(
            model_name='producttag',
            name='image',
            field=models.ImageField(null=True, upload_to='tag-image'),
        ),
        migrations.AddField(
            model_name='producttag',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='tag-thumbnail'),
        ),
    ]
